### ISSUE TITLE
Model csv file

### ISSUE THREAD

**Issue by 010722** [ShenCiao/Ciallo#5]
By the way, can I ask that how you store the model csv file (any transformation for the coordinates)? Since the x and y coordinates are somehow mainly distributed around negative two and positive two (I did a simple test and found the min is -2 and max is 8 roughly). The paths in my dataset have the points with coordinations between 0 and 800 for a 800*800 pixel png...

**Comment by 010722** [comment]
(But it seems alright to import directly my dataset with the same data arrangement format in csv, haha)

**Comment by ShenCiao** [comment]
Sorry to disappoint you. I didn't implement the code to store the csv file. Those files are exported from Blender Grease Pencil with a dirty python script.

Check out for https://cloud.blender.org/p/gallery/5b642e25bf419c1042056fc6, you will what's your need.

**Comment by ShenCiao** [comment]
The script to iterate through the GP strokes and points if you need them:
```
import numpy as np

n_strokePoints = np.array([], dtype = int)

d = C.object.data
n_v = 0
for l in d.layers:
    f = l.frames[0]
    print("layer name: {}".format(l.info))
    print("number of strokes {}".format(len(f.strokes)))
    n_vertices = 0
    for s in f.strokes:
        n_vertices += len(s.points)
        n_strokePoints = np.append(n_strokePoints, len(s.points))
    print("number of vertices {}".format(n_vertices))
    n_v += n_vertices
    
print("all vertices {}".format(n_v))
```

**Comment by 010722** [comment]
Got it, thanks for your detailed explanation. I'm doing a project based on Ciallo so there is a high chance that problems, big and small, will arise these days... Thanks again and in advance for your kindly help.
